# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp\xe9rature')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de relev\xe9')),
            ],
        ),
    ]
