# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hygrometrie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hygro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hygrom\xe9trie')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de relev\xe9')),
            ],
        ),
        migrations.CreateModel(
            name='Soil_moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidit\xe9 du sol')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de relev\xe9')),
            ],
        ),
    ]
